import { createFileRoute } from "@tanstack/react-router";
import { LegalPageShell } from "@/components/site-footer";

export const Route = createFileRoute("/terms")({
  component: TermsPage,
  head: () => ({
    meta: [
      { title: "Terms of Service — Creator's Muse" },
      { name: "description", content: "The terms that govern your use of Creator's Muse." },
    ],
  }),
});

function TermsPage() {
  return (
    <LegalPageShell title="Terms of Service" updated="May 2026">
      <Section title="1. Acceptance of terms">
        By creating an account or using Creator's Muse ("the Service"), you agree to these terms. If you do not agree, do not use the Service.
      </Section>
      <Section title="2. The Service">
        Creator's Muse provides AI-assisted content generation tools for creators, including hook generation, captions, reel ideation, and workflow management. AI output is generated by third-party language models and is provided as-is.
      </Section>
      <Section title="3. Your account">
        You are responsible for safeguarding your credentials and for any activity under your account. You must be at least 16 years old to use the Service.
      </Section>
      <Section title="4. Acceptable use">
        You agree not to use the Service to generate unlawful, harmful, harassing, defamatory, or infringing content. You may not attempt to reverse engineer, abuse, or overwhelm the AI endpoints or quotas.
      </Section>
      <Section title="5. Content ownership">
        You retain ownership of content you submit and of AI output generated for you, subject to the rights granted to the underlying model providers. You are responsible for verifying suitability before publishing.
      </Section>
      <Section title="6. Plans & billing">
        Free accounts include a monthly credit allowance. Paid plans will be offered via secure third-party checkout once billing launches publicly. Usage is metered server-side; abuse may result in suspension.
      </Section>
      <Section title="7. Termination">
        We may suspend or terminate accounts that violate these terms. You may delete your account at any time from Settings.
      </Section>
      <Section title="8. Disclaimers">
        The Service is provided "as is" without warranties of any kind. We do not guarantee virality, engagement, or fitness for any particular purpose.
      </Section>
      <Section title="9. Contact">
        Questions about these terms? Reach us via the <a href="/contact" className="text-primary hover:underline">contact page</a>.
      </Section>
    </LegalPageShell>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="mb-2 text-base font-semibold text-foreground">{title}</h2>
      <p>{children}</p>
    </section>
  );
}
